version: "3.8"
services:
  db-todo:
    image: postgres:12.2
    network_mode: bridge
    container_name: todo_pg
    volumes:
      - db-todo-data:/var/lib/postgresql/data
    expose:
      - 5431
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo
    restart: unless-stopped
volumes:
  db-todo-data:
